[package]
name = "typst-docx"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.5.1"
anyhow = "1.0.82"
arboard = "3.3.2"
fs2 = "0.4.3"
uuid = { version = "1.8.0", features = ["v4"] }
